export const OPEN_SIDE_BAR = 'OPEN_SIDE_BAR';
export const CLOSE_SIDE_BAR = 'CLOSE_SIDE_BAR';
export const LOGIN_AS_STUEDENT_ACTION = 'IS_STUEDENT_LOGGEDIN';
export const LOGOUT_AS_STUDENT_ACTION = 'LOGOUT_AS_STUDENT_ACTION';